title: CreateVoterCardApplicationMessage
type: object
description: >
  Message used to create a Voter Card Application, sent from IER to EROP
  This must be kept in sync with EROP's copy at
  https://github.com/communitiesuk/eip-ero-voter-card-applications-api/blob/main/src/main/resources/openapi/sqs/vca-api-sqs-messaging-ier.yaml#L54
x-api-owner: IER
x-api-consumer: EROP
properties:
  id:
    type: string
    pattern: '^[a-fA-F\d]{24}$'
    description: 'The unique IER identifier for this application. A 24 character hex string.'
  gssCode:
    $ref: ./Primatives/GssCode.yaml
  applicationReference:
    type: string
    description: 'The application reference as known by the citizen. Not guaranteed to be unique.'
  datetimeSubmitted:
    type: string
    format: date-time
  firstName:
    type: string
    maxLength: 255
  middleNames:
    type: string
    maxLength: 255
  surname:
    type: string
    maxLength: 255
  dateOfBirth:
    type: string
    format: date
  registeredWithUnknownDob:
    type: boolean
  unknownDobReason:
    type: string
  ageRange:
    $ref: ./AgeRange.yaml
    # Only required for applications where DOB not known
  email:
    type: string
    format: email
    maxLength: 256
  phoneNumber:
    type: string
    maxLength: 50
    description: >
      Contact phone number. Must be a string of no more than 50 characters,
      containing only numbers or characters which match /[\s+\-_\\()A-Za-z]/.
      After removing non-numeric characters, it must contain between 5 and 30 digits.
  noContact:
    type: boolean
    default: false
  nino:
    type: string
    maxLength: 10
  cantSupplyNinoReason:
    type: string
    maxLength: 500
  address:
    $ref: ./Address.yaml
  overseasAddress:
    $ref: ./OverseasAddress.yaml
  cardIssuingPreferences:
    $ref: ./CardIssuingPreferences.yaml
  identityDocuments:
    type: array
    items:
      $ref: ./DocumentReference.yaml
  photo:
    $ref: ./PhotoReference.yaml
  submittedInWelsh:
    type: boolean
    default: false
  alternativeFormatNeeded:
    $ref: ./AlternativeFormat.yaml
  applicantIpAddress:
    type: string
    maxLength: 45
    description: The IP address of the applicant when completing their application on the IER web application front end. May be either an IPv4 or IPv6 address.
  recentlyAppliedToRtv:
    type: boolean
    description: Indicates that the applicant may have a pending register to vote application; the truth of this cannot be guaranteed as it is based on the applicant's answer to a question.
  isDuplicate:
    type: boolean
    description: Indicates that the application was detected as a duplicate, but the applicant decided to submit it anyway.
required:
  - id
  - gssCode
  - applicationReference
  - datetimeSubmitted
  - firstName
  - surname
  - cardIssuingPreferences
  - address
  - photo
  - submittedInWelsh
  - recentlyAppliedToRtv
  - isDuplicate
  - applicantIpAddress