title: CreateProxyVoteApplicationMessage
type: object
description: >
  Message used to create a Proxy Vote Application, sent from IER to EROP
  This must be kept in sync with EROP's copy at
  https://github.com/communitiesuk/eip-ero-proxy-applications-api/blob/main/src/main/resources/openapi/sqs/proxy-api-sqs-messaging-ier.yaml#L44
x-api-owner: IER
x-api-consumer: EROP
properties:
  id:
    type: string
    pattern: '^[a-fA-F\d]{24}$'
    description: 'The unique IER identifier for this application. A 24 character hex string.'
  gssCode:
    $ref: ./Primatives/GssCode.yaml
  applicationReference:
    type: string
    description: 'The application reference as known by the citizen. Not guaranteed to be unique.'
  datetimeSubmitted:
    type: string
    format: date-time
  proxyVoteReason:
    # This captures the type of voter, see detailed comments in ProxyReason.yaml
    $ref: ./ProxyReason.yaml
  proxyVoteReasonAdditionalText:
    type: string
    maxLength: 500
    description: 'This is only populated when proxyVoteReason = other'
  proxyVoteType:
    # Proxy Vote duration types
    $ref: ./ProxyVoteType.yaml
  specificDate:
    type: string
    format: date
    description: 'This is only populated when ProxyVoteType = specific-date'
  dateRangeStart:
    type: string
    format: date
    description: 'This is only populated when ProxyVoteType = specific-date-range'
  dateRangeEnd:
    type: string
    format: date
    description: 'This is only populated when ProxyVoteType = specific-date-range'
  firstName:
    type: string
    maxLength: 35
  middleNames:
    type: string
    maxLength: 100
  surname:
    type: string
    maxLength: 35
  hasPreviousName:
    $ref: ./HasPreviousName.yaml
  previousName:
    $ref: ./PreviousName.yaml
  dateOfBirth:
    type: string
    format: date
  nino:
    type: string
    maxLength: 10
  cantSupplyNinoReason:
    type: string
    maxLength: 500
  address:
    $ref: ./Address.yaml
  email:
    type: string
    format: email
    maxLength: 255
  phoneNumber:
    type: string
    maxLength: 50
    description: >
      Contact phone number. Must be a string of no more than 50 characters,
      containing only numbers or characters which match /[\s+\-_\\()A-Za-z]/.
      After removing non-numeric characters, it must contain between 5 and 30 digits.
  noContact:
    type: boolean
    default: false
  proxyFirstName:
    type: string
    maxLength: 35
  proxyMiddleNames:
    type: string
    maxLength: 100
  proxySurname:
    type: string
    maxLength: 35
  proxyAddress:
    $ref: ./Address.yaml
  proxyEmail:
    type: string
    format: email
    maxLength: 255
  proxyPhoneNumber:
    type: string
    maxLength: 50
    description: >
      Contact phone number for proxy. Must be a string of no more than 50 characters,
      containing only numbers or characters which match /[\s+\-_\\()A-Za-z]/.
      After removing non-numeric characters, it must contain between 5 and 30 digits.
  signatureImage:
    type: string
    format: byte
    description: >
      The processed signature image to be used on the application.
      This has been processed by cropping, scaling and thresholding to black & white. Format is base64 PNG, 1050x300px, monochrome.
      We also send the original uploaded photo in the 'signatureImageFile' field, in case this processing has outputted
      an unusable image and re-processing in the EROP is needed.
  signatureImageFile:
    $ref: ./DocumentReference.yaml
    description: >
      The original signature image uploaded by the user.
      We also send a processed version in the 'signatureImage' field.
      This can be used in the EROP to re-process the signature if processed signature is unusable.
  requestedSignatureWaiver:
    type: boolean
    description: >
      Either requestedSignatureWaiver & reasonCannotSignNameConsistently will be provided
      and signatureImage & signatureImageFile will be omitted OR
      signatureImage & signatureImageFile will be provided
      and requestedSignatureWaiver & reasonCannotSignNameConsistently will be omitted.
  reasonCannotSignNameConsistently:
    type: string
    maxLength: 327
    description: > 
      This is only populated when requestedSignatureWaiver is true.
      If the user has selected that they cannot read or write, this field is filled with the text "I cannot read or write".
      Otherwise, the max length comprises 250 characters from a free text field, prefixed with the text 
      "I have a disability that prevents me from signing or uploading my signature: ".
  identityDocuments:
    type: array
    items:
      $ref: ./DocumentReference.yaml
  submittedInWelsh:
    type: boolean
    default: false
  applicantIpAddress:
    type: string
    maxLength: 45
    description: The IP address of the applicant when completing their application on the IER web application front end. An optional value that if provided may be either an IPv4 or IPv6 address.
  isDuplicate:
    type: boolean
    description: Indicates that the application was detected as a duplicate, but the applicant decided to submit it anyway.
  hadHelpWithApplication:
    type: boolean
    description: Whether the applicant had help with their application. Only populated if requestedSignatureWaiver is true.
  helperDetails:
    $ref: ./HelperDetails.yaml
    description: Populated when hadHelpWithApplication is true.
required:
  - id
  - gssCode
  - applicationReference
  - datetimeSubmitted
  - proxyVoteReason
  - proxyVoteType
  - firstName
  - surname
  - hasPreviousName
  - dateOfBirth
  - address
  - proxyFirstName
  - proxySurname
  - proxyAddress
  - applicantIpAddress
  - submittedInWelsh
  - isDuplicate