description: >
  The ERO Portal should send this message to IER if an application is deleted.
  As the other fields get removed upon deletion on the ERO Portal side, 
  this has to be sent as a separate message with just the id and applicationDeletedDate.
title: UpdateApplicationStatisticsDeletedDateMessage
type: object
properties:
  id:
    type: string
    pattern: '^[a-fA-F\d]{24}$'
    description: 'The unique IER identifier for this application. A 24 character hex string.'
  applicationDeletedDate:
    type: string
    format: date-time
    description: Date at which the application was deleted
required:
  - id
  - applicationDeletedDate