name: Build a tagged version and deploy to ECR

on:
  workflow_dispatch:

jobs:
  deploy:
    if: startsWith(github.ref, 'refs/tags/v')
    uses: communitiesuk/eip-ero-shared-workflows/.github/workflows/build-and-push.yml@main
    with:
      version: ${{ github.ref_name }}
      image_name: eip-ero-${{ vars.app_name }}
      ecr_repo: ${{ vars.app_name }}-repo
      preprod_deploy_environment: dev2 # All envs can use dev2 GitHub role
    secrets: inherit
